### PR TITLE
use; thrown \Glitch

### PR DESCRIPTION
**Pull request by szepeviktor**
@betterthanclay Could you point out where the `\Glitch` class is defined?

props. @phpstan `phpstan analyze --level=max src/`

### CODE REVIEW

**Comment by betterthanclay** [comment]
Hi Viktor, thanks for contributing.
The "use Df\Flex\Formatter;" line needs to be removed, agreed, that was left in by mistake.

However, the Glitch library uses a Facade mechanism (using the Veneer library - https://github.com/decodelabs/veneer) to alias the class into the current namespace automatically and so doesn't require an import at all. It could be namespaced under "use DecodeLabs\Glitch;" to avoid the aliasing, but this is not necessary for the code to work.

**Comment by szepeviktor** [comment]
All right.

If you would like to benefit from static analysis - it seems like - you need to create the phpstan-veneer package :)

**Comment by betterthanclay** [comment]
Yeah, there's quite a bit of extra work that will need to go with the Veneer library, it's still early in development. We will be adding unit tests, examples and other supporting materials soon; I'll look into adding better support for phpstan.

**Comment by szepeviktor** [comment]
I work for developer teams. I talk them into using the following zero-coverage tests in CI:

1. syntax check
2. coding standard (much more than how you indent your code!)
3. static analysis

It makes your code robust without writing a single test.

**Comment by szepeviktor** [comment]
> However, the Glitch library uses a Facade mechanism (using the Veneer library - [decodelabs/veneer](https://github.com/decodelabs/veneer)) to alias the class into the current namespace automatically

@betterthanclay Could you tell me a bit more about `\Glitch`? It is the `function Glitch($message, ?array $params=[], $data=null): \EGlitch` from glitch's helpers.php? I'd like to learn it.

**Comment by betterthanclay** [comment]
Hi Viktor.

Ok so the interface is actually made up of three components - that global Glitch function, a <code>__call()</code> method on the main Glitch Context class and the Veneer facade that offers a static reference to that context, with a <code>__callStatic</code> method in place to pass dynamic calls through to the context object.

The most common usage of the Glitch exception generator is to pass the name of the exception you want to generate as the method name: 

<code>throw Glitch::ERuntime('message', $prams);</code>

This calls the facade statically, gets passed through to the Context object <code>__call</code>, which then creates an exception factory and the output is actually created - in the example above, the generated exception would include an ERuntime interface in its type definition.

The global Glitch function is there just as a fallback for when you don't want to define the type of exception at all and generate the most generic type of Glitch exception -

<code>throw Glitch('message');</code>

It doesn't actually get used very much as usually you would want to define a type but it's there for the edge cases where you don't.

I'm happy to explain any parts in more detail if it's not clear - there are a handful of different systems all working together and it's tricky to explain it all in one go.

**Comment by szepeviktor** [comment]
Thank you very much!

How about putting this in a _How Glitch works_ section in https://github.com/decodelabs/glitch/blob/develop/README.md ?

**Comment by betterthanclay** [comment]
The key aspect of it is using <code>__callStatic</code> as a means of using method names as arbitrary parameters - especially when you consider you can use strings using brackets..

<code>Class::{'any old info'}();</code>

The Tagged library in the decodelabs account uses the same premise for generating html tags..

<code>Html::{'div.container#content'}('My container div');</code>

I'll do a more detailed writeup for the Glitch docs as you suggest as it will help people get a better idea of how to use it if nothing else.

**Comment by szepeviktor** [comment]
> The Tagged library in the decodelabs account uses the same premise for generating html tags..

What a coincident! I also have a tag factory https://gist.github.com/szepeviktor/5020f75cf5704ae70ba97ba3049048db although it is much lighter.

**Comment by betterthanclay** [comment]
Yeah, it makes life a lot easier when you're putting together templates having those sorts of functions available.

Up to you whether you want to revisit your library, but you can get quite a lot of extra functionality out of it by supporting Generators..

You could add something like this before <code>$content</code> is appended to $html in your tag function - 

```php
if($content instance of \Traversable) {
    $content = implode(iterator_to_array($content));
}
```

That way, you can encapsulate tag logic within anonymous functions and use <code>yield</code> like you would use echo with only a fairly trivial change to the code. It can help tidy up template code quite considerably.

```php
echo tag('div', [], function() {
    yield 'Text content';
    yield tag('div', ['class' => 'inner'], 'Inner content');
});

**Comment by szepeviktor** [comment]
Thank you, I try to implement that.

**Comment by betterthanclay** [comment]
FYI, I've added a detailed explanation of the Glitch interface to the docs via the README (link at the bottom) - let me know if anything is unclear :)

**Pull request merged**
